services:
  timetrex:
    build: .
    ports:
      - 8080:80
    links:
      - postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
  postgres:
    image: postgres:13-bullseye
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: timetrex
      POSTGRES_USER: timetrex
      POSTGRES_PASSWORD: password

volumes:
  postgres:
